// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfiabuawusbzirlaqixo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmaWFidWF3dXNiemlybGFxaXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5NzQ0NjgsImV4cCI6MjA4NjU1MDQ2OH0.16kSjRwqHlBBGDnbGH7p4I4IKVaA6oLL0uZLvAzBE5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});